//
// ConnectAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ConnectAPI {

    /**

     - returns: GetTonConnectPayload200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getTonConnectPayload() async throws -> GetTonConnectPayload200Response {
        return try await getTonConnectPayloadWithRequestBuilder().execute().body
    }

    /**
     - GET /tonconnect/payload
     - Get a payload for further token receipt
     - returns: RequestBuilder<GetTonConnectPayload200Response> 
     */
    open class func getTonConnectPayloadWithRequestBuilder() -> RequestBuilder<GetTonConnectPayload200Response> {
        let localVariablePath = "/tonconnect/payload"
        let localVariableURLString = BatteryAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetTonConnectPayload200Response>.Type = BatteryAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
