//
// AndroidBatteryPurchaseStatusPurchasesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AndroidBatteryPurchaseStatusPurchasesInner: Codable, JSONEncodable, Hashable {

    public var productId: String
    public var token: String
    public var success: Bool
    public var error: AndroidBatteryPurchaseStatusPurchasesInnerError?

    public init(productId: String, token: String, success: Bool, error: AndroidBatteryPurchaseStatusPurchasesInnerError? = nil) {
        self.productId = productId
        self.token = token
        self.success = success
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productId = "product_id"
        case token
        case success
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(productId, forKey: .productId)
        try container.encode(token, forKey: .token)
        try container.encode(success, forKey: .success)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

