//
// AndroidBatteryPurchaseStatusPurchasesInnerError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AndroidBatteryPurchaseStatusPurchasesInnerError: Codable, JSONEncodable, Hashable {

    public enum Code: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case invalidProductId = "invalid-product-id"
        case userNotFound = "user-not-found"
        case purchaseIsAlreadyUsed = "purchase-is-already-used"
        case temporaryError = "temporary-error"
        case unknown = "unknown"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var msg: String
    public var code: Code

    public init(msg: String, code: Code) {
        self.msg = msg
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case msg
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(msg, forKey: .msg)
        try container.encode(code, forKey: .code)
    }
}

