//
// ApplyPromoRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApplyPromoRequest: Codable, JSONEncodable, Hashable {

    public var publicKey: String
    public var promoCode: String

    public init(publicKey: String, promoCode: String) {
        self.publicKey = publicKey
        self.promoCode = promoCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publicKey = "public_key"
        case promoCode = "promo_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publicKey, forKey: .publicKey)
        try container.encode(promoCode, forKey: .promoCode)
    }
}

