//
// Balance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Balance: Codable, JSONEncodable, Hashable {

    public enum Units: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case usd = "usd"
        case ton = "ton"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var balance: String
    /** reserved amount in units (TON/USD) */
    public var reserved: String
    public var units: Units

    public init(balance: String, reserved: String, units: Units) {
        self.balance = balance
        self.reserved = reserved
        self.units = units
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case balance
        case reserved
        case units
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(balance, forKey: .balance)
        try container.encode(reserved, forKey: .reserved)
        try container.encode(units, forKey: .units)
    }
}

