//
// BatteryCharged.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BatteryCharged: Codable, JSONEncodable, Hashable {

    public var batteryCharged: Bool

    public init(batteryCharged: Bool) {
        self.batteryCharged = batteryCharged
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case batteryCharged = "battery_charged"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(batteryCharged, forKey: .batteryCharged)
    }
}

