//
// CreatePromoCampaign200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreatePromoCampaign200Response: Codable, JSONEncodable, Hashable {

    public var participants: [CreatePromoCampaign200ResponseParticipantsInner]

    public init(participants: [CreatePromoCampaign200ResponseParticipantsInner]) {
        self.participants = participants
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case participants
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(participants, forKey: .participants)
    }
}

