//
// CreatePromoCampaign200ResponseParticipantsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreatePromoCampaign200ResponseParticipantsInner: Codable, JSONEncodable, Hashable {

    public var address: String
    public var balanceIncreased: String?
    public var error: String?

    public init(address: String, balanceIncreased: String? = nil, error: String? = nil) {
        self.address = address
        self.balanceIncreased = balanceIncreased
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case balanceIncreased = "balance_increased"
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encodeIfPresent(balanceIncreased, forKey: .balanceIncreased)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

