//
// CreateCustomRefundRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCustomRefundRequest: Codable, JSONEncodable, Hashable {

    public var relayerEventId: Int?
    public var amount: String
    public var currency: String
    public var comment: String
    public var reason: String
    public var destination: String

    public init(relayerEventId: Int? = nil, amount: String, currency: String, comment: String, reason: String, destination: String) {
        self.relayerEventId = relayerEventId
        self.amount = amount
        self.currency = currency
        self.comment = comment
        self.reason = reason
        self.destination = destination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case relayerEventId = "relayer_event_id"
        case amount
        case currency
        case comment
        case reason
        case destination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(relayerEventId, forKey: .relayerEventId)
        try container.encode(amount, forKey: .amount)
        try container.encode(currency, forKey: .currency)
        try container.encode(comment, forKey: .comment)
        try container.encode(reason, forKey: .reason)
        try container.encode(destination, forKey: .destination)
    }
}

