//
// CreatePromoCampaignRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreatePromoCampaignRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var participants: [CreatePromoCampaignRequestParticipantsInner]

    public init(name: String, participants: [CreatePromoCampaignRequestParticipantsInner]) {
        self.name = name
        self.participants = participants
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case participants
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(participants, forKey: .participants)
    }
}

