//
// EnterpriseWalletConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EnterpriseWalletConfig: Codable, JSONEncodable, Hashable {

    /** when building a message to transfer an NFT or Jetton, use this address to send excess funds back to Battery Service. */
    public var excessAccount: String

    public init(excessAccount: String) {
        self.excessAccount = excessAccount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case excessAccount = "excess_account"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(excessAccount, forKey: .excessAccount)
    }
}

