//
// EnterpriseGetStatus200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EnterpriseGetStatus200Response: Codable, JSONEncodable, Hashable {

    public var balance: String
    public var wallet: String

    public init(balance: String, wallet: String) {
        self.balance = balance
        self.wallet = wallet
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case balance
        case wallet
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(balance, forKey: .balance)
        try container.encode(wallet, forKey: .wallet)
    }
}

