//
// EnterpriseEstimateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EnterpriseEstimateRequest: Codable, JSONEncodable, Hashable {

    public var boc: String
    public var walletPublicKey: String

    public init(boc: String, walletPublicKey: String) {
        self.boc = boc
        self.walletPublicKey = walletPublicKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case boc
        case walletPublicKey = "wallet_public_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(boc, forKey: .boc)
        try container.encode(walletPublicKey, forKey: .walletPublicKey)
    }
}

