//
// EnterpriseEstimate200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EnterpriseEstimate200Response: Codable, JSONEncodable, Hashable {

    public var estimatedUpfrontPayment: String
    /** base64 encoded emulation results. The exact type can be taken from /v2/wallet/emulate (TONAPI). */
    public var emulation: String?

    public init(estimatedUpfrontPayment: String, emulation: String? = nil) {
        self.estimatedUpfrontPayment = estimatedUpfrontPayment
        self.emulation = emulation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case estimatedUpfrontPayment = "estimated_upfront_payment"
        case emulation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(estimatedUpfrontPayment, forKey: .estimatedUpfrontPayment)
        try container.encodeIfPresent(emulation, forKey: .emulation)
    }
}

