//
// EnterpriseSend200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EnterpriseSend200Response: Codable, JSONEncodable, Hashable {

    public var msgId: String

    public init(msgId: String) {
        self.msgId = msgId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case msgId = "msg_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(msgId, forKey: .msgId)
    }
}

