//
// EstimatedTronTxInstantFeeAcceptedAssetsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EstimatedTronTxInstantFeeAcceptedAssetsInner: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case jetton = "jetton"
        case ton = "ton"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var name: String
    public var jettonMasterId: String?
    public var amountNano: String
    public var decimals: Int

    public init(type: ModelType, name: String, jettonMasterId: String? = nil, amountNano: String, decimals: Int) {
        self.type = type
        self.name = name
        self.jettonMasterId = jettonMasterId
        self.amountNano = amountNano
        self.decimals = decimals
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case name
        case jettonMasterId = "jetton_master_id"
        case amountNano = "amount_nano"
        case decimals
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(jettonMasterId, forKey: .jettonMasterId)
        try container.encode(amountNano, forKey: .amountNano)
        try container.encode(decimals, forKey: .decimals)
    }
}

