//
// EstimateGaslessCostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EstimateGaslessCostRequest: Codable, JSONEncodable, Hashable {

    public var battery: Bool? = true
    public var payload: String

    public init(battery: Bool? = true, payload: String) {
        self.battery = battery
        self.payload = payload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case battery
        case payload
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(battery, forKey: .battery)
        try container.encode(payload, forKey: .payload)
    }
}

