//
// EstimatedTronTxInstantFee.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EstimatedTronTxInstantFee: Codable, JSONEncodable, Hashable {

    public var feeAddress: String
    public var acceptedAssets: [EstimatedTronTxInstantFeeAcceptedAssetsInner]

    public init(feeAddress: String, acceptedAssets: [EstimatedTronTxInstantFeeAcceptedAssetsInner]) {
        self.feeAddress = feeAddress
        self.acceptedAssets = acceptedAssets
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case feeAddress = "fee_address"
        case acceptedAssets = "accepted_assets"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(feeAddress, forKey: .feeAddress)
        try container.encode(acceptedAssets, forKey: .acceptedAssets)
    }
}

