//
// EstimatedTronTx.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EstimatedTronTx: Codable, JSONEncodable, Hashable {

    public var energyCharges: Int
    public var bandwidthCharges: Int
    public var activationCharges: Int
    public var totalCharges: Int

    public init(energyCharges: Int, bandwidthCharges: Int, activationCharges: Int, totalCharges: Int) {
        self.energyCharges = energyCharges
        self.bandwidthCharges = bandwidthCharges
        self.activationCharges = activationCharges
        self.totalCharges = totalCharges
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case energyCharges = "energy_charges"
        case bandwidthCharges = "bandwidth_charges"
        case activationCharges = "activation_charges"
        case totalCharges = "total_charges"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(energyCharges, forKey: .energyCharges)
        try container.encode(bandwidthCharges, forKey: .bandwidthCharges)
        try container.encode(activationCharges, forKey: .activationCharges)
        try container.encode(totalCharges, forKey: .totalCharges)
    }
}

