//
// GaslessEstimation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GaslessEstimation: Codable, JSONEncodable, Hashable {

    public var commission: String

    public init(commission: String) {
        self.commission = commission
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commission
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(commission, forKey: .commission)
    }
}

