//
// GetTronConfig200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTronConfig200Response: Codable, JSONEncodable, Hashable {

    public var safetyMarginPercent: String

    public init(safetyMarginPercent: String) {
        self.safetyMarginPercent = safetyMarginPercent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case safetyMarginPercent = "safety_margin_percent"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(safetyMarginPercent, forKey: .safetyMarginPercent)
    }
}

