//
// IncreaseUserBalanceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IncreaseUserBalanceRequest: Codable, JSONEncodable, Hashable {

    /** amount in TON to increase balance by */
    public var amount: String
    /** reason for balance increase */
    public var reason: String?

    public init(amount: String, reason: String? = nil) {
        self.amount = amount
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(reason, forKey: .reason)
    }
}

