//
// IosBatteryPurchaseRequestTransactionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IosBatteryPurchaseRequestTransactionsInner: Codable, JSONEncodable, Hashable {

    public var id: String
    public var promo: String?

    public init(id: String, promo: String? = nil) {
        self.id = id
        self.promo = promo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case promo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(promo, forKey: .promo)
    }
}

