//
// IOSBatteryPurchaseStatusTransactionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IOSBatteryPurchaseStatusTransactionsInner: Codable, JSONEncodable, Hashable {

    public var transactionId: String
    public var success: Bool
    public var error: IOSBatteryPurchaseStatusTransactionsInnerError?

    public init(transactionId: String, success: Bool, error: IOSBatteryPurchaseStatusTransactionsInnerError? = nil) {
        self.transactionId = transactionId
        self.success = success
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactionId = "transaction_id"
        case success
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(transactionId, forKey: .transactionId)
        try container.encode(success, forKey: .success)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

