//
// ManualTransferRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ManualTransferRequest: Codable, JSONEncodable, Hashable {

    /** Relayer wallet address to send from */
    public var relayer: String
    /** Recipient address */
    public var to: String
    /** Currency code ('TON', 'USD₮', 'jUSDT', etc.) */
    public var currency: String
    /** Amount in currency units (not nano) */
    public var amount: String
    /** Optional text comment for TON transfers */
    public var comment: String?

    public init(relayer: String, to: String, currency: String, amount: String, comment: String? = nil) {
        self.relayer = relayer
        self.to = to
        self.currency = currency
        self.amount = amount
        self.comment = comment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case relayer
        case to
        case currency
        case amount
        case comment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(relayer, forKey: .relayer)
        try container.encode(to, forKey: .to)
        try container.encode(currency, forKey: .currency)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(comment, forKey: .comment)
    }
}

