//
// PromoCodeBatteryPurchaseRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PromoCodeBatteryPurchaseRequest: Codable, JSONEncodable, Hashable {

    public var promoCode: String

    public init(promoCode: String) {
        self.promoCode = promoCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case promoCode = "promo_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(promoCode, forKey: .promoCode)
    }
}

