//
// PromoUsed.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PromoUsed: Codable, JSONEncodable, Hashable {

    public var promoUsed: Bool

    public init(promoUsed: Bool) {
        self.promoUsed = promoUsed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case promoUsed = "promo_used"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(promoUsed, forKey: .promoUsed)
    }
}

