//
// PromoCodeBatteryPurchaseStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PromoCodeBatteryPurchaseStatus: Codable, JSONEncodable, Hashable {

    public var balanceChange: String
    public var success: Bool
    public var error: PromoCodeBatteryPurchaseStatusError?

    public init(balanceChange: String, success: Bool, error: PromoCodeBatteryPurchaseStatusError? = nil) {
        self.balanceChange = balanceChange
        self.success = success
        self.error = error
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case balanceChange = "balance_change"
        case success
        case error
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(balanceChange, forKey: .balanceChange)
        try container.encode(success, forKey: .success)
        try container.encodeIfPresent(error, forKey: .error)
    }
}

