//
// Purchases.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Purchases: Codable, JSONEncodable, Hashable {

    public var totalPurchases: Int
    public var purchases: [PurchasesPurchasesInner]

    public init(totalPurchases: Int, purchases: [PurchasesPurchasesInner]) {
        self.totalPurchases = totalPurchases
        self.purchases = purchases
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalPurchases = "total_purchases"
        case purchases
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalPurchases, forKey: .totalPurchases)
        try container.encode(purchases, forKey: .purchases)
    }
}

