//
// PurchasesPurchasesInnerRefundInformationRefunded.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PurchasesPurchasesInnerRefundInformationRefunded: Codable, JSONEncodable, Hashable {

    public var amount: String
    public var charges: Int

    public init(amount: String, charges: Int) {
        self.amount = amount
        self.charges = charges
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case charges
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(charges, forKey: .charges)
    }
}

