//
// RechargeMethods.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RechargeMethods: Codable, JSONEncodable, Hashable {

    public var methods: [RechargeMethodsMethodsInner]

    public init(methods: [RechargeMethodsMethodsInner]) {
        self.methods = methods
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case methods
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(methods, forKey: .methods)
    }
}

