//
// Status.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Status: Codable, JSONEncodable, Hashable {

    public var pendingTransactions: [StatusPendingTransactionsInner]

    public init(pendingTransactions: [StatusPendingTransactionsInner]) {
        self.pendingTransactions = pendingTransactions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pendingTransactions = "pending_transactions"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pendingTransactions, forKey: .pendingTransactions)
    }
}

