//
// TransactionsTransactionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TransactionsTransactionsInner: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case pending = "pending"
        case completed = "completed"
        case failed = "failed"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var id: String
    /** represents the amount of money paid by the user for this transaction. */
    public var paidAmount: String
    public var status: Status
    public var createdAt: String

    public init(id: String, paidAmount: String, status: Status, createdAt: String) {
        self.id = id
        self.paidAmount = paidAmount
        self.status = status
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case paidAmount = "paid_amount"
        case status
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(paidAmount, forKey: .paidAmount)
        try container.encode(status, forKey: .status)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension TransactionsTransactionsInner: Identifiable {}
