//
// Transactions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Transactions: Codable, JSONEncodable, Hashable {

    public var totalTransactions: Int
    /** if set, then there are more transactions to be loaded. Use this value as offset parameter in the next request. */
    public var nextOffset: Int?
    public var transactions: [TransactionsTransactionsInner]

    public init(totalTransactions: Int, nextOffset: Int? = nil, transactions: [TransactionsTransactionsInner]) {
        self.totalTransactions = totalTransactions
        self.nextOffset = nextOffset
        self.transactions = transactions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalTransactions = "total_transactions"
        case nextOffset = "next_offset"
        case transactions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalTransactions, forKey: .totalTransactions)
        try container.encodeIfPresent(nextOffset, forKey: .nextOffset)
        try container.encode(transactions, forKey: .transactions)
    }
}

