//
// TronSendRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TronSendRequest: Codable, JSONEncodable, Hashable {

    public var tx: String?
    public var energy: Int?
    public var bandwidth: Int?
    public var wallet: String

    public init(tx: String? = nil, energy: Int? = nil, bandwidth: Int? = nil, wallet: String) {
        self.tx = tx
        self.energy = energy
        self.bandwidth = bandwidth
        self.wallet = wallet
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tx
        case energy
        case bandwidth
        case wallet
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tx, forKey: .tx)
        try container.encodeIfPresent(energy, forKey: .energy)
        try container.encodeIfPresent(bandwidth, forKey: .bandwidth)
        try container.encode(wallet, forKey: .wallet)
    }
}

