//
// TronAvailableTransfers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TronAvailableTransfers: Codable, JSONEncodable, Hashable {

    /** Number of available free TRON transfers */
    public var availableTransfers: Int
    /** Availability type. 'inactive' if source is telegram. */
    public var type: String
    /** Unix timestamp of next free transfers reset date (either next month after last reset or next charge date, whichever is closer) */
    public var nextResetDate: Int64?

    public init(availableTransfers: Int, type: String, nextResetDate: Int64? = nil) {
        self.availableTransfers = availableTransfers
        self.type = type
        self.nextResetDate = nextResetDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case availableTransfers = "available_transfers"
        case type
        case nextResetDate = "next_reset_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(availableTransfers, forKey: .availableTransfers)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(nextResetDate, forKey: .nextResetDate)
    }
}

