//
// VerifyPurchasePromo200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VerifyPurchasePromo200Response: Codable, JSONEncodable, Hashable {

    public var bonusCharges: String

    public init(bonusCharges: String) {
        self.bonusCharges = bonusCharges
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bonusCharges = "bonus_charges"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bonusCharges, forKey: .bonusCharges)
    }
}

